version: "3.9"

services:
  web:
    build: .
    container_name: fgp-blog-web
    ports:
      - "3001:80"
    environment:
      - VITE_BASE_URL=${VITE_NEWS_API}
      - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
    restart: unless-stopped
